version: 2.1
jobs:
  checkout_code:
    docker:
      - image: circleci/flutter:latest
    steps:
      - checkout
  install_dependencies:
    docker:
      - image: circleci/flutter:latest
    steps:
      - run:
          name: Install Dependencies
          command: flutter pub get
  lint:
    docker:
      - image: circleci/flutter:latest
    steps:
      - run:
          name: Run Flutter Analyzer
          command: flutter analyze
  build_ios:
    macos:
      xcode: "12.0.0"
    steps:
      - run:
          name: Build iOS
          command: flutter build ios --release --no-codesign
  build_android:
    docker:
      - image: circleci/flutter:latest
    steps:
      - run:
          name: Build Android
          command: flutter build apk --release
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - install_dependencies
      - lint
      - build_ios
      - build_android

